Contributions from ugent.be migration
collective/collective.jsonify pull request #45
Opened 2020-09-07 17:23 UTC by zopyx

2020-11-25 10:47 UTC, thet approved these changes
LGTM

2023-01-29 09:53 UTC, pbauer requested changes

2023-01-29 09:53 UTC, pbauer commented on collective/jsonify/browser.py
> +        except Exception as e:
This breaks Python 2.4 support

2023-01-29 09:53 UTC, pbauer commented on collective/jsonify/export.py
> +
Please remove debug-print

2023-01-29 09:53 UTC, pbauer commented on collective/jsonify/export.py
> +        except Exception as e:
This breaks Python 2.4 support

2023-01-29 09:53 UTC, pbauer commented on collective/jsonify/export.py
> +            except Exception as error:
This breaks Python 2.4 support

2023-01-29 09:53 UTC, pbauer commented on collective/jsonify/methods.py
> +    except Exception as e:
see above

2023-01-29 09:53 UTC, pbauer commented on collective/jsonify/methods.py
> +        except Exception as error:
see above

2023-01-29 09:53 UTC, pbauer commented on collective/jsonify/wrapper.py
> +        from plone.portlets.interfaces import IPortletManager
I think adding imports from plone.portlets breaks support for plone versions older than 3.0

2023-04-21 11:40 UTC, closed without merging